"""add image_filename to Post

Revision ID: 956b1dc5f6e1
Revises: 
Create Date: 2025-10-30 09:00:07.509955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956b1dc5f6e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
